### ISSUE TITLE
I installed this theme and migrated to nody and know the only thing i see is a black screen.

### ISSUE THREAD

**Issue by GerardPolloRebozado** [mshernandez5/WelcomeXP#12]
I was using the lightdm-webkit2 so I uninstalled and installed nody and changed the theme and set the greeter to nody, after that, I restarted to try it out, and now the only thing it appears is a black screen with a white hyphen. Using CTRL+ F2 F3 F4 F5 doesn't open the terminal.

**Comment by mshernandez5** [comment]
What distribution are you using?

The common keyboard shortcut to switch to a different TTY is `CTRL+ALT+F2`, `CTRL+ALT+F3`, etc. (basically any one that isn't already reserved by the graphical session). Don't forget the `ALT` key if you're trying to switch over. That should get you to what is basically an emergency terminal.

When you installed nody-greeter, did you make sure to also edit `/etc/lightdm/lightdm.conf` or (depending on your distribution) one of the configuration files in `/etc/lightdm/lightdm.conf.d/` and change `greeter-session=web-greeter` to `greeter-session=nody-greeter`?
