### ISSUE TITLE
Will this be ported to KDE Plasma?

### ISSUE THREAD

**Issue by EndreEndi** [mshernandez5/WelcomeXP#20]
As the title says.
I'm on Debian 12 KDE Plasma and love Windows XP, i would love this as my Login Screen when i start my laptop.

**Comment by mshernandez5** [comment]
Sorry, there is no plan to rewrite the theme for SDDM - the greeter generally used with KDE Plasma.
It is still possible to use this theme with a KDE desktop but it involves replacing your current greeter with lightdm before installing nody-greeter or WelcomeXP.
