### ISSUE TITLE
enter login field more easily [feature request]

### ISSUE THREAD

**Issue by TheFlipside** [mshernandez5/WelcomeXP#6]
i like this theme very much

it would make everyday use easier though if i was able to enter the password input field by pressing ENTER or TAB
not sure how in detail it would work with multiple users

also when in the password field or the shutdown menu it would be nice to be able to go back by pressing ESC

**Comment by mshernandez5** [comment]
Glad you like the theme!
I fully agree these features would be nice.
I am currently working on another project but can look into this pretty soon.

Will reference this issue when I make any relevant changes so updates should show on this post.

**Comment by mshernandez5** [comment]
Got some time, added tab key to switch users (it focuses to the password field so you can quickly select and login to the first user) and escape key to exit the shutdown options overlay.

**Comment by TheFlipside** [comment]
thank you, this is a very nice improvement
